<!DOCTYPE html>
<!--[if IE 8 ]>
<html class="no-js ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>
<html class="no-js ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->

<head lang="en">
    <meta charset="UTF-8">

    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1, shrink-to-fit=no">


    <title>Aegis</title>
    <link rel="shortcut icon" href="<?php echo $this->baseUrl("publiczone/images/favicon.ico");?>" type="image/x-icon"">
    <link rel="icon" href="<?php echo $this->baseUrl("publiczone/images/favicon.ico");?>" type="image/x-icon">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl("publiczone/css/bootstrap.css");?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl("publiczone/css/style.css");?>">

    <!--[if lt IE 9]>
    <script src="<?php echo $this->baseUrl("publiczone/bootstrap/js/html5shiv.min.js");?>"></script>
    <script src="<?php echo $this->baseUrl("publiczone/bootstrap/js/respond.min.js") ;?>"></script>

    <![endif]-->

    <script src="<?php echo $this->baseUrl("publiczone/js/modernizr.custom.js");?>"></script>
</head>


<body class="cssAnimate navbar--transparent navbar--fixedTop navbar-onepage">


<div class="ct-navbarMobile ct-u-bgBlack">
    <button type="button" class="navbar-toggle">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
</div>

<div class="ct-menuMobile">
    <ul class="ct-menuMobile-navbar list-unstyled ct-u-backgroundDarkGray">
        <li><a href="#home">Home</a></li>
        <li><a href="#products">Prodotti</a></li>
        <li><a href="#contatti">Contatti</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'index'),null,true); ?>">Login</a></li>
    </ul>
</div>

<div id="ct-js-wrapper">
    <header class="ct-mainHeader">

        <div class="ct-topBar topBar--type1">
            <div class="navbar navbar-default">
                <div class="container ct-navbar-container">
                    <p class="navbar-text navbar-left"><i class="fa fa-phone"></i> Supporto: 0732 - 80 90 60</p>
                    <p class="navbar-text navbar-right">Benvenuti!</p>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-default navbar--type2 ">

            <div class="container ct-navbar-container">


                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url(array(
                        "controller" => "index",
                        "action" => "index",
                    ));?>"">
                        <img class="navbar-brand-defaultColor" alt="Brand" src="<?php echo $this->baseUrl("publiczone/images/demo-content/logo.png");?>"/>
                    </a>
                </div>

                <ul class="nav navbar-nav navbar-left ct-navbar--fadeInLeft">
                    <li class="onepage active"><a href="#home">Home</a></li>
                    <li class="onepage"><a href="#products">Prodotti</a></li>
                    <li class="onepage"><a href="#contatti">Contattaci</a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'index'),null,true); ?>"><b>Login</b></a></li>
                </ul>
            </div>
        </nav>
    </header>

    <main>

        <div class="container">
            <section class="ct-u-marginTop70 ct-u-marginBottom70 section" id="home">

                <div class="row">
                    <div class="col-lg-8">

                        <section class="ct-js-slick is-loading ct-slick ct-slick-arrow--type3 ct-u-marginBottom30"
                                 data-autoplay="false" data-arrows="true" data-items="1" data-XSitems="1"
                                 data-SMitems="1" data-MDitems="1">
                            <div class="item">
                                <article class="ct-imageBox ct-u-paddingBoth0">
                                    <figure class="ct-imageBox-wrapperOuter">
                                        <div class="ct-imageBox-container">
                                            <img src="<?php echo $this->baseUrl("publiczone/images/demo-content/image4.jpg");?>" alt="">
                                        </div>
                                        <figcaption class="ct-imageBox-wrapperInner ct-imageBox-wrapperInner--type1">
                                            <div class="ct-imageBox-titleContainer">
                                                <header class="ct-imageBox-title">

                                                    <h3>
                                                        <span>la <b>nostra</b></span>
                                                        <span>idea di</span>
                                                    </h3>
                                                    <h1>
                                                        <span>innovazione</span>
                                                        <span>agricola</span>
                                                    </h1>

                                                    <div class="text-right">
                                                        <a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'index'),null,true); ?>" class="btn btn-lg ct-btn-image btn-warning"><span>Effettua il Login</span></a>
                                                    </div>
                                                </header>

                                            </div>
                                        </figcaption>
                                    </figure>
                                </article>
                            </div>

                        </section>

                    </div>
                    <div class="col-lg-4">
                        <div class="row">
                            <div class="col-lg-12 col-md-6 col-sm-6">
                                <article class="ct-imageBox">
                                    <a title="image">
                                        <figure class="ct-imageBox-wrapperOuter">
                                            <div class="ct-imageBox-container">
                                                <img src="<?php echo $this->baseUrl("publiczone/images/demo-content/image2.jpg");?>" alt="">
                                                <div class="ct-decoration ct-decoration--type1">
                                                    <div>
                                                        <div class="ct-decoration-textContainer">
                                                            <div class="ct-decoration-text">
                                                                <h4><span>dispositivo</span></h4>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <figcaption
                                                class="ct-imageBox-wrapperInner ct-imageBox-wrapperInner--type2">
                                                <div class="ct-imageBox-titleContainer">
                                                    <header class="ct-imageBox-title-light">
                                                        <h2><span>un semplice</span></h2>
                                                    </header>
                                                </div>
                                            </figcaption>
                                        </figure>
                                    </a>
                                </article>
                            </div>
                            <div class="col-lg-12 col-md-6 col-sm-6">
                                <article class="ct-imageBox">
                                        <figure class="ct-imageBox-wrapperOuter">
                                            <div class="ct-imageBox-container">
                                                <img src="<?php echo $this->baseUrl("publiczone/images/demo-content/image1.jpg");?>" alt="">
                                                <div class="ct-decoration ct-decoration--type2">
                                                    <div class="ct-imageBox-titleContainer">
                                                        <div class="ct-decoration-textContainer">
                                                            <div class="ct-decoration-text">
                                                                <header>
                                                                    <h2 class="ct-u-marginBoth0"><span>buona</span></h2>
                                                                    <h4 class="ct-u-marginBottom20">
                                                                        <span>produzione</span></h4>
                                                                </header>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <figcaption
                                                class="ct-imageBox-wrapperInner ct-imageBox-wrapperInner--type3">
                                                <div class="ct-imageBox-titleContainer">
                                                    <header class="ct-imageBox-title-light">
                                                        <h2><span>per una</span></h2>
                                                    </header>
                                                </div>
                                            </figcaption>
                                            <figcaption class="ct-imageBox-wrapperInner">

                                            </figcaption>
                                        </figure>
                                </article>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>

        <section class="container section" id="products">
            <h3 class="ct-headline text-center">
        <span class="ct-headline-container ct-u-colorMotive">
            <span class="ct-headline-line ct-headline-line--left"></span>
                prodotti
            <span class="ct-headline-line ct-headline-line--right"></span>
        </span>
            </h3>
        </section>

        <section class="ct-u-marginTop70 ct-u-marginBottom70">
            <div class="container ct-u-marginBottom80">

                <article class="ct-event-item ct-event-item--type1">

                    <div class="ct-event-item-outer">
                        <div class="ct-event-item-media">
                            <figure>
                                <div id="synced-1" class="ct-slick--synced ct-slick--synced--type2">
                                    <div class="ct-slick ct-js-slick ct-js-slick-for" data-items="1" data-arrows="false"
                                         data-draggable="false" data-touchMove="false">
                                        <div class="item"><a class="ct-js-magnificPopupImage"
                                                             href="<?php echo $this->baseUrl("publiczone/images/demo-content/olive1.jpg");?>"
                                                             title="image1"><img
                                                    src="<?php echo $this->baseUrl("publiczone/images/demo-content/olive1.jpg");?>" alt=""/></a></div>
                                        <div class="item"><a class="ct-js-magnificPopupImage"
                                                             href="<?php echo $this->baseUrl("publiczone/images/demo-content/olive2.jpg");?>"
                                                             title="image2"><img
                                                    src="<?php echo $this->baseUrl("publiczone/images/demo-content/olive2.jpg");?>" alt=""/></a></div>
                                        <div class="item"><a class="ct-js-magnificPopupImage"
                                                             href="<?php echo $this->baseUrl("publiczone/images/demo-content/olive3.jpg");?>"
                                                             title="image3"><img
                                                    src="<?php echo $this->baseUrl("publiczone/images/demo-content/olive3.jpg");?>" alt=""/></a></div>
                                        <div class="item"><a class="ct-js-magnificPopupImage"
                                                             href="<?php echo $this->baseUrl("publiczone/images/demo-content/olive4.jpg");?>"
                                                             title="image4"><img
                                                    src="<?php echo $this->baseUrl("publiczone/images/demo-content/olive4.jpg");?>" alt=""/></a></div>
                                        <div class="item"><a class="ct-js-magnificPopupImage"
                                                             href="<?php echo $this->baseUrl("publiczone/images/demo-content/olive5.jpg");?>"
                                                             title="image5"><img
                                                    src="<?php echo $this->baseUrl("publiczone/images/demo-content/olive5.jpg");?>" alt=""/></a></div>
                                    </div>
                                    <div class="ct-slick ct-js-slick ct-js-slick-nav ct-slick-arrow--type4 ct-slick-thumbnailHover--type2"
                                         data-items="2" data-centerMode="true" data-centerPadding="0"
                                         data-asNavFor="#synced-1 .ct-js-slick-for" data-XSitems="2" data-SMitems="4"
                                         data-focusOnSelect="true">
                                        <div class="item"><img src="<?php echo $this->baseUrl("publiczone/images/demo-content/olive1.jpg");?>" alt=""/>
                                        </div>
                                        <div class="item"><img src="<?php echo $this->baseUrl("publiczone/images/demo-content/olive2.jpg");?>" alt=""/>
                                        </div>
                                        <div class="item"><img src="<?php echo $this->baseUrl("publiczone/images/demo-content/olive3.jpg");?>" alt=""/>
                                        </div>
                                        <div class="item"><img src="<?php echo $this->baseUrl("publiczone/images/demo-content/olive4.jpg");?>" alt=""/>
                                        </div>
                                        <div class="item"><img src="<?php echo $this->baseUrl("publiczone/images/demo-content/olive5.jpg");?>" alt=""/>
                                        </div>
                                    </div>
                                </div>
                            </figure>
                        </div>

                        <div class="ct-event-item-wrapper">

                            <div class="ct-event-item-inner">
                                <section>
                                    <div class="ct-event-title">
                                        <h6><span>Protezione continua per i tuoi ulivi</span></h6>
                                    </div>

                                    <div class="ct-event-text">
                                        <p>
                                            Il nostro sistema innovativo permette di monitorare lo stato di ampi terreni
                                            agricoli direttamente
                                            da casa tua. Mediante l'utilizzo di telecamere e sensori, posizionati
                                            strategicamente, in simbiosi
                                            con un software di ultima generazione, siamo in grado di valutare il rischio
                                            di attacco in una determinata
                                            zona permettendo di intervenire in tempo per salvare le piante. Per una
                                            maggiore tutela dell'ambiente,
                                            l'alimentazione dei sensori è completamente ecosostenibile e sfrutta
                                            l'energia solare immagazzinata
                                            tramite pannelli solari.
                                        </p>
                                    </div>

                                    <div class="text-left">
                                        <a href="#" class="btn ct-btn-image btn-warning"><span>Scopri di più</span></a>
                                    </div>
                                </section>
                            </div>
                        </div>
                    </div>

                    <div class="clearfix"></div>
                </article>


            </div>
        </section>


        <section class="container section" id="contatti">
            <h3 class="ct-headline text-center">
        <span class="ct-headline-container ct-u-colorMotive">
            <span class="ct-headline-line ct-headline-line--left"></span>
                contattaci
            <span class="ct-headline-line ct-headline-line--right"></span>
        </span>
            </h3>
        </section>

        <section class="ct-u-marginTop70 ct-u-marginBottom70">
            <div class="container">
                <div class="row">

                    <div class="container text-center">
                        <br>
                        <br>

                        <div class="row">
                            <div class="col-md-12 col-sm-6 ct-u-marginBottom30">
                                <h3 class="ct-u-colorYellow ct-u-ff--2 text-uppercase ct-u-marginBottom30">servizio ai
                                    clienti</h3>
                                <h6 class="ct-u-colorBrownDark2 text-uppercase ct-fw-600 ct-u-size13 ct-u-marginBottom15">
                                    Telefono</h6>

                                <p class="ct-u-colorGray ct-u-marginBottom10">071.80.90.60</p>
                                <p class="ct-u-colorGray ct-u-marginBottom20">Dal Lunedì al Venerdì, dalle 7:00 a.m.
                                    alle 6:00 p.m.
                                </p>

                                <p class="ct-u-colorMotive ct-u-marginBottom25 text-uppercase">Non ci hai trovati?
                                    Lasciate un messaggio;
                                    controlliamo i messaggi vocali sette giorni su sette.</p>

                                <h6 class="ct-u-colorBrownDark2 text-uppercase ct-fw-600 ct-u-size13 ct-u-marginBottom15">
                                    Email</h6>

                                <p class="ct-u-colorGray">aedis@freeenergy.com</p>

                            </div>
                            <div class="col-md-12 col-sm-6 ct-u-marginBottom30">
                                <h3 class="ct-u-colorYellow text-uppercase ct-u-ff--2 ct-u-marginBottom30">INDIRIZZO
                                    POSTALE</h3>
                                <h6 class="ct-u-colorBrownDark2 text-uppercase ct-fw-600 ct-u-size13 ct-u-marginBottom15">
                                    Aedis SRLS (Ancona AN)</h6>

                                <p class="ct-u-colorGray ct-u-marginBottom10">99, Baraccola 2</p>
                                <p class="ct-u-colorGray ct-u-marginBottom30">CAP 60120</p>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

    <footer>

        <div class="ct-postFooter">
            <div class="container">
                <div class="ct-u-displayTableVertical">
                    <div class="ct-u-displayTableCell text-left">
                        <p class="ct-u-marginBoth0 ct-u-colorWhite">© 2016 Aegis. Tutti i diritti riservati.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>

<a href="#" class="ct-js-btnScrollUp"><i class="fa fa-angle-up"></i></a>
<script src="<?php echo $this->baseUrl("publiczone/js/jquery.min.js");?>"></script>
<script src="<?php echo $this->baseUrl("publiczone/js/dependencies.js");?>"></script>
<script src="<?php echo $this->baseUrl("publiczone/bootstrap/js/bootstrap.min.js");?>"></script>
<script src="<?php echo $this->baseUrl("publiczone/plugins/slick/slick.min.js");?>"></script>
<script src="<?php echo $this->baseUrl("publiczone/plugins/slick/init.js");?>"></script>

<script src="<?php echo $this->baseUrl("publiczone/twitter/js/jquery.tweet.js");?>"></script>
<script src="<?php echo $this->baseUrl("publiczone/form/js/contact-form.js");?>"></script>

<script src="<?php echo $this->baseUrl("publiczone/js/ct-mediaSection/jquery.stellar.min.js");?>"></script>
<script src="<?php echo $this->baseUrl("publiczone/js/ct-mediaSection/init.js");?>"></script>

<script src="<?php echo $this->baseUrl("publiczone/js/onepager/jquery.pagescroller.lite.js");?>"></script>
<script src="<?php echo $this->baseUrl("publiczone/js/onepager/init.js");?>"></script>

<script src="<?php echo $this->baseUrl("publiczone/js/portfolio/jquery.isotope.min.js");?>"></script>
<script src="<?php echo $this->baseUrl("publiczone/js/portfolio/imagesloaded.js");?>"></script>
<script src="<?php echo $this->baseUrl("publiczone/js/portfolio/init.js");?>"></script>

<script src="<?php echo $this->baseUrl("publiczone/js/magnific-popup/jquery.magnific-popup.min.js");?>"></script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
<script src="<?php echo $this->baseUrl("publiczone/js/gmap/gmap3.min.js");?>"></script>

<script src="<?php echo $this->baseUrl("publiczone/js/counter/jquery.countTo.js");?>"></script>

<script src="<?php echo $this->baseUrl("publiczone/js/main.js");?>"></script>

</body>

</html>