<!DOCTYPE html>
<html>

<head lang="it">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>TITOLO</title>

    <link href="<?php echo $this->baseUrl("img/favicon.144x144.html"); ?>" rel="apple-touch-icon" type="image/png"
          sizes="144x144">
    <link href="<?php echo $this->baseUrl("img/favicon.114x114.html"); ?>" rel="apple-touch-icon" type="image/png"
          sizes="114x114">
    <link href="<?php echo $this->baseUrl("img/favicon.72x72.html"); ?>" rel="apple-touch-icon" type="image/png"
          sizes="72x72">
    <link href="<?php echo $this->baseUrl("img/favicon.57x57.html"); ?>" rel="apple-touch-icon" type="image/png">
    <link href="<?php echo $this->baseUrl("img/favicon.html"); ?>" rel="icon" type="image/png">
    <link href="<?php echo $this->baseUrl("img/favicon-2.html"); ?>" rel="shortcut icon">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/separate/vendor/fancybox.min.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/separate/pages/activity.min.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/lib/font-awesome/font-awesome.min.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/lib/bootstrap/bootstrap.min.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/main.css"); ?>">
</head>
<body class="with-side-menu control-panel control-panel-compact">

<header class="site-header">
    <div class="container-fluid">

        <a href="#" class="site-logo">
            <img class="hidden-md-down" src="<?php echo $this->baseUrl("img/logo-2.png"); ?>" alt="">
            <img class="hidden-lg-up" src="<?php echo $this->baseUrl("img/logo-2-mob.png"); ?>" alt="">
        </a>
        
</header><!--.site-header-->

<div class="mobile-menu-left-overlay"></div>

<div class="page-content">
    <div class="container-fluid">
        <!-- page content -->
        <?php echo $this->layout()->content; ?>
    </div><!--.container-fluid-->
</div><!--.page-content-->
<script src="<?php echo $this->baseUrl("js/lib/jquery/jquery.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/lib/tether/tether.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/lib/bootstrap/bootstrap.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/plugins.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/lib/fancybox/jquery.fancybox.pack.js"); ?>"></script>
<script>
    $(function () {
        $(".fancybox").fancybox({
            padding: 0,
            openEffect: 'none',
            closeEffect: 'none'
        });
    });
</script>
<script src="<?php echo $this->baseUrl("js/app.js"); ?>"></script>
</body>

</html>