<!DOCTYPE html>
<html>

<head lang="it">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Aegis</title>

    <link href="<?php echo $this->baseUrl("img/favicon.144x144.html"); ?>" rel="apple-touch-icon" type="image/png"
          sizes="144x144">
    <link href="<?php echo $this->baseUrl("img/favicon.114x114.html"); ?>" rel="apple-touch-icon" type="image/png"
          sizes="114x114">
    <link href="<?php echo $this->baseUrl("img/favicon.72x72.html"); ?>" rel="apple-touch-icon" type="image/png"
          sizes="72x72">
    <link href="<?php echo $this->baseUrl("img/favicon.57x57.html"); ?>" rel="apple-touch-icon" type="image/png">
    <link href="<?php echo $this->baseUrl("img/favicon.html"); ?>" rel="icon" type="image/png">
    <link href="<?php echo $this->baseUrl("img/favicon-2.html"); ?>" rel="shortcut icon">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/separate/vendor/fancybox.min.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/separate/pages/activity.min.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/lib/font-awesome/font-awesome.min.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/lib/bootstrap/bootstrap.min.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/main.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl("css/select2.min.css"); ?>">
</head>
<body class="with-side-menu control-panel control-panel-compact">

<header class="site-header">
    <div class="container-fluid">

        <a href="#" class="site-logo">
            <img class="hidden-md-down" src="<?php echo $this->baseUrl("img/logo-2.png"); ?>" alt="">
            <img class="hidden-lg-up" src="<?php echo $this->baseUrl("img/logo-2-mob.png"); ?>" alt="">
        </a>

        <button id="show-hide-sidebar-toggle" class="show-hide-sidebar">
            <span>toggle menu</span>
        </button>

        <button class="hamburger hamburger--htla">
            <span>toggle menu</span>
        </button>
        <div class="site-header-content">
            <div class="site-header-content-in">
                <div class="site-header-shown">
                    <div class="dropdown dropdown-notification notif">
                        <a href="#"
                           class="header-alarm dropdown-toggle active"
                           id="dd-notification"
                           data-toggle="dropdown"
                           aria-haspopup="true"
                           aria-expanded="false">
                            <i class="font-icon-alarm"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-notif"
                             aria-labelledby="dd-notification">
                            <div class="dropdown-menu-notif-header">
                                Notifications

                            </div>
                            <div class="dropdown-menu-notif-list">
                                <?php
                                foreach ($this->elenconotifiche as $notifiche): ?>
                                    <div class="dropdown-menu-notif-item">
                                        <div class="photo">
                                            <img src="img/photo-64-1.jpg" alt="">
                                        </div>
                                        <div class="dot"></div>
                                        <a href="#"><?php echo $notifiche->titolo; ?></a>
                                        <div class="color-blue-grey-lighter"></div><?php echo $notifiche->ora; ?>
                                    </div>
                                <?php endforeach; ?>


                            </div>
                            <div class="dropdown-menu-notif-more">
                                <a href="#">See more</a>
                            </div>
                        </div>
                    </div>


                    <div class="dropdown user-menu">
                        <button class="dropdown-toggle" id="dd-user-menu" type="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            <img src="<?php echo $this->baseUrl("img/avatar-2-64.png") ?>" alt="">
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dd-user-menu">
                            <a class="dropdown-item" href="<?php echo $this->url(
                                array('controller' => $this->role, 'action' => 'modificaprofilo')) ?>"><span
                                    class="font-icon glyphicon glyphicon-user"></span>Modifica
                                Profilo</a>
                            <a class="dropdown-item" href="#"><span class="font-icon glyphicon glyphicon-cog"></span>Impostazioni</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="<?php echo $this->url(
                                array('controller' => 'login', 'action' => 'logout')) ?>"><span
                                    class="font-icon glyphicon glyphicon-log-out"></span>Logout</a>
                        </div>
                    </div>

                </div><!--.site-header-shown-->

                <div class="mobile-menu-right-overlay"></div>
                <div class="site-header-collapsed">

                </div><!--.site-header-collapsed-->
            </div><!--site-header-content-in-->
        </div><!--.site-header-content-->
    </div><!--.container-fluid-->
</header><!--.site-header-->

<div class="mobile-menu-left-overlay"></div>
<nav class="side-menu">
    <ul class="side-menu-list">
        <li class="giulia-pink">
	            <span>
	                <i class="font-icon font-icon-dashboard"></i>
	                <span class="lbl">Dashboard</span>
	            </span>
        </li>

        <li class="giulia-beige">
            <a href="<?php echo $this->url(
                array('controller' => $this->role, 'action' => 'modificaprofilo')) ?>">
                   <span>
                        <i class="font-icon font-icon-user"></i>
                        <span class="lbl">Modifica Profilo</span>
                   </span>
            </a>
        </li>
        <li class="orange-red">
            <a href="<?php echo $this->url(array("controller" => "user", "action" => "impostazionisensori")); ?>">
                <span>
	                <i class="fa fa-cogs"></i>
                    <span class="lbl">Impostazioni sensori</span>
                </span>
            </a>
        </li>

        <!-- menu admin -->
        <hr>
        <li class="orange-red with-sub">
	            <span>
	                <i class="fa fa-pagelines"></i>
	                <span class="lbl">Gestione Uliveti</span>
	            </span>
            <ul>
                <li><a href="<?php echo $this->url(array("controller" => "admin", "action" => "elencouliveti")); ?>"><span class="lbl">Gestione uliveti</span></a></li>
                <li>
                    <a href="<?php echo $this->url(array("controller" => "admin", "action" => "gestioneappezzamenti")); ?>"><span
                            class="lbl">Gestione appezzamenti</span></a></li>
                <li><a href="<?php echo $this->url(array("controller" => "admin", "action" => "visualizzanodi")); ?>"><span class="lbl">Gestioni nodi</span></a></li>
            </ul>
        </li>


        <li class="giulia-pink">
            <a href="<?php
            echo $this->url(
                array(
                    'controller' => 'admin',
                    'action' => 'gestionemalfunzionamenti',
                ), null, true
            ) ?>">
                <i class="font-icon font-icon-help"></i>
                <span class="lbl">Gestione malfunziamenti</span>
            </a>
        </li>


    </ul>
</nav><!--.side-menu-->

<div class="page-content">
    <div class="container-fluid">
        <!-- page content -->
        <?php echo $this->layout()->content; ?>
    </div><!--.container-fluid-->
</div><!--.page-content-->
<script src="<?php echo $this->baseUrl("js/lib/jquery/jquery.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/lib/tether/tether.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/lib/bootstrap/bootstrap.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/plugins.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/lib/fancybox/jquery.fancybox.pack.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("vendor/flot/jquery.flot.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("vendor/flot/flot-time-plugin.js"); ?>"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script>
    $(function () {
        $(".fancybox").fancybox({
            padding: 0,
            openEffect: 'none',
            closeEffect: 'none'
        });
    });
</script>
<script src="<?php echo $this->baseUrl("js/app.js"); ?>"></script>

<?php if ($this->currentPage == "index"): ?>
    <script>
        $(document).ready(function () {
            graficoTemperatura()
            graficoMosche()
            graficoUmidita()
        });

        function graficoTemperatura() {
            //dichiaro il carattere " come pattern, e re come espressione regolare. lo userò per rimpiazzarla globalmente


            //data = [[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26]];
            data = <?php echo $this->datitemperatura; ?>;
            // data = [[1, 3], [2, 14.01], [3.5, 3.14]];
            s = [{
                data: data,
                color: '#f0c54c'
            }]

            $.plot($("#temperatura"), s, {
                grid: {borderWidth: 1, color: "rgba(0,0,0,0.02)"},
                yaxis: {
                    minTickSize: 1,
                    tickDecimals: 0,
                    mode: "categories",
                    tickLength: 0,
                    axisLabelUseCanvas: !0,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: "inherit"
                },
                xaxis: {
                    minTickSize: [1, "day"],
                    mode: "time",
                    timeformat: "%d/%m/%y"
                }
            });


        }

        function graficoUmidita() {
            //dichiaro il carattere " come pattern, e re come espressione regolare. lo userò per rimpiazzarla globalmente


            //data = [[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26]];
            data = <?php echo $this->datiUmidita; ?>;
            // data = [[1, 3], [2, 14.01], [3.5, 3.14]];
            s = [{
                data: data,
                color: '#f0c54c'
            }]


            $.plot($("#umidita"), s, {
                grid: {borderWidth: 1, color: "rgba(0,0,0,0.02)"},
                yaxis: {
                    minTickSize: 1,
                    tickDecimals: 0,
                    mode: "categories",
                    tickLength: 0,
                    axisLabelUseCanvas: !0,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: "inherit"
                },
                xaxis: {
                    minTickSize: [1, "day"],
                    mode: "time",
                    timeformat: "%d/%m/%y"
                }
            });


        }

        function graficoMosche() {
            //dichiaro il carattere " come pattern, e re come espressione regolare. lo userò per rimpiazzarla globalmente


            //data = [[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26],[new Date(2012, 1, 1), 26]];
            data = <?php echo $this->datiConta; ?>;
            // data = [[1, 3], [2, 14.01], [3.5, 3.14]];
            s = [{
                data: data,
                color: '#f0c54c'
            }]


            $.plot($("#mosche"), s, {
                grid: {borderWidth: 1, color: "rgba(0,0,0,0.02)"},
                yaxis: {
                    minTickSize: 1,
                    tickDecimals: 0,
                    mode: "categories",
                    tickLength: 0,
                    axisLabelUseCanvas: !0,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: "inherit"
                },
                xaxis: {
                    minTickSize: [1, "day"],
                    mode: "time",
                    timeformat: "%d/%m/%y"
                }
            });


        }
        (jQuery);
    </script>
<?php endif; ?>

</body>

</html>