<!DOCTYPE html>
<html>



<!-- Mirrored from themesanytime.com/startui/demo/activity.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 18 Nov 2016 18:25:41 GMT -->
<head lang="en">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>StartUI - Premium Bootstrap 4 Admin Dashboard Template</title>

	<link href="img/favicon.144x144.html" rel="apple-touch-icon" type="image/png" sizes="144x144">
	<link href="img/favicon.114x114.html" rel="apple-touch-icon" type="image/png" sizes="114x114">
	<link href="img/favicon.72x72.html" rel="apple-touch-icon" type="image/png" sizes="72x72">
	<link href="img/favicon.57x57.html" rel="apple-touch-icon" type="image/png">
	<link href="img/favicon.html" rel="icon" type="image/png">
	<link href="img/favicon-2.html" rel="shortcut icon">

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	<link rel="stylesheet" href="css/separate/vendor/fancybox.min.css">
	<link rel="stylesheet" href="css/separate/pages/activity.min.css">
	<link rel="stylesheet" href="css/lib/font-awesome/font-awesome.min.css">
	<link rel="stylesheet" href="css/lib/bootstrap/bootstrap.min.css">
	<link rel="stylesheet" href="css/main.css">
</head>

<body class="with-side-menu">

<div class="mobile-menu-left-overlay"></div>


<div>
	<?php
	foreach($this->arraynotifiche as $notifica):
		?>
		<div class="container-fluid">
			<section class="activity-line">
				<article class="activity-line-item box-typical">
					<div class="activity-line-date">
						<?php echo $notifica->data; ?>
					</div>
					<header class="activity-line-item-header">
						<div class="activity-line-item-user-name"><?php echo $this->utente; ?></div>
					</header>
					<div class="activity-line-action-list">
						<section class="activity-line-action">
							<div class="time"><?php echo $notifica->ora; ?></div>
							<div class="cont">
								<div class="cont-in">
									<h5><b><?php echo $notifica->titolo; ?></b></h5>
									<p><?php echo $notifica->descrizione; ?></p>

								</div>
							</div>
						</section><!--.activity-line-action-->
					</div><!--.activity-line-action-list-->
				</article><!--.activity-line-item-->
			</section><!--.activity-line-->
		</div><!--.container-fluid-->
		<?php
	endforeach;
	?>
</div><!--.page-content-->

<script src="js/lib/jquery/jquery.min.js"></script>
<script src="js/lib/tether/tether.min.js"></script>
<script src="js/lib/bootstrap/bootstrap.min.js"></script>
<script src="js/plugins.js"></script>
<script src="js/lib/fancybox/jquery.fancybox.pack.js"></script>
<script>
	$(function() {
		$(".fancybox").fancybox({
			padding: 0,
			openEffect	: 'none',
			closeEffect	: 'none'
		});
	});
</script>
<script src="js/app.js"></script>
</body>

<!-- Mirrored from themesanytime.com/startui/demo/activity.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 18 Nov 2016 18:25:42 GMT -->
</html>