<!DOCTYPE html>
<html>

<body class="with-side-menu">

<div class="mobile-menu-left-overlay"></div>


<div>
	<?php
	foreach($this->arraynotifiche as $notifica):
		?>
		<div class="container-fluid">
			<section class="activity-line">
				<article class="activity-line-item box-typical">
					<div class="activity-line-date">
						<?php echo $notifica->data; ?>
					</div>
					<header class="activity-line-item-header">
						<div class="activity-line-item-user-name"><?php echo $this->utente; ?></div>
					</header>
					<div class="activity-line-action-list">
						<section class="activity-line-action">
							<div class="time"><?php echo $notifica->ora; ?></div>
							<div class="cont">
								<div class="cont-in">
									<h5><b><?php echo $notifica->titolo; ?></b></h5>
									<p><?php echo $notifica->descrizione; ?></p>

								</div>
							</div>
						</section><!--.activity-line-action-->
					</div><!--.activity-line-action-list-->
				</article><!--.activity-line-item-->
			</section><!--.activity-line-->
		</div><!--.container-fluid-->
		<?php
	endforeach;
	?>
</div><!--.page-content-->

</body>

</html>