<?php echo $this->appezzamento->nome; ?>
<br>
<br>
<br>
<div class="col-md-8" style="height:800px">
    <object height="90%" width="100%" type="image/svg+xml"
            data="<?php echo $this->baseUrl($this->appezzamento->mappa); ?>"
            pluginspage="http://www.adobe.com/svg/viewer/install/">
    </object>

</div>
<div class="col-md-4">
    <?php echo $this->appezzamento->note; ?>
</div>





