<!-- GESTIONE GRAFICI -->
   <div class="col-md-12">
       <div class="card" id="graphs">
           <div class="card-block">
               <div class="m-b-1">

                   <h6>Conta delle mosche</h6></div>
               <div id="mosche"class="dashboard-line chart" style="height:300px"></div>
           </div>
       </div>
   </div>
   <div class="col-md-12">
       <div class="card" id="graphs">
           <div class="card-block">
               <div class="m-b-1">

                   <h6>Grafico della temperatura</h6></div>
               <div id="temperatura" class="dashboard-line chart" style="height:300px"></div>
           </div>
       </div>
   </div>
   <div class="col-md-12">
       <div class="card" id="graphs">
           <div class="card-block">
               <div class="m-b-1">

                   <h6>Grafico dell'umidità</h6></div>
               <div id="umidita" class="dashboard-line chart" style="height:300px"></div>
           </div>
       </div>
   </div>
