<?php
$rosso = "color:#e74c3c";
$arancione = "color:#e67e22";
$verde = "color:#2ecc71";
$grigio = "color: #95a5a6";
?>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">

            <tr class="bg-danger">
                <th class="text-center">Nome</th>
                <th class="text-center">Visualizza</th>
            </tr>

            <tbody>
            <?php foreach ($this->elencoAppezzamenti as $appezzamenti): ?>
                <tr>
                    <td style="text-align:center;"><?php echo $appezzamenti->nome; ?></td>

                    <td style="text-align:center;">
                        <a href="<?php echo $this->url(array(
                                "controller" => "admin",
                                "action" => "visualizzanodi",
                                "uliveto" => $this->uliveto,
                                "appezzamento" => $appezzamenti->idappezzamento
                                )
                        );
                        ?>">
                            <button class="btn btn-warning">Visualizza Appezzamento</button>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <br><br>
        <div align="center">
            <td style="text-align:center;">
                <a href="<?php echo $this->url(array(
                        "controller" => "admin",
                        "action" => "inseriscinodo")

                )
                ?>">
                    <button class="btn btn-success">Inserisci Nodo</button>
                </a>
            </td>
        </div>
    </div>
</div>





