<!DOCTYPE html>
<html>

<!-- Mirrored from themesanytime.com/startui/demo/activity.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 18 Nov 2016 18:25:41 GMT -->
<head lang="en">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>StartUI - Premium Bootstrap 4 Admin Dashboard Template</title>

	<link href="img/favicon.144x144.html" rel="apple-touch-icon" type="image/png" sizes="144x144">
	<link href="img/favicon.114x114.html" rel="apple-touch-icon" type="image/png" sizes="114x114">
	<link href="img/favicon.72x72.html" rel="apple-touch-icon" type="image/png" sizes="72x72">
	<link href="img/favicon.57x57.html" rel="apple-touch-icon" type="image/png">
	<link href="img/favicon.html" rel="icon" type="image/png">
	<link href="img/favicon-2.html" rel="shortcut icon">

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	<link rel="stylesheet" href="css/separate/vendor/fancybox.min.css">
	<link rel="stylesheet" href="css/separate/pages/activity.min.css">
	<link rel="stylesheet" href="css/lib/font-awesome/font-awesome.min.css">
	<link rel="stylesheet" href="css/lib/bootstrap/bootstrap.min.css">
	<link rel="stylesheet" href="css/main.css">
</head>

<body class="with-side-menu">

<

<div class="mobile-menu-left-overlay"></div>


<div class="page-content">
	<div class="container-fluid">
		<section class="activity-line">
			<article class="activity-line-item box-typical">
				<div class="activity-line-date">
					Tuesday<br/>
					sep 9
				</div>
				<header class="activity-line-item-header">
					<div class="activity-line-item-user">
						<div class="activity-line-item-user-photo">
							<a href="#">
								<img src="img/photo-64-2.jpg" alt="">
							</a>
						</div>
						<div class="activity-line-item-user-name">Tim Colins</div>
						<div class="activity-line-item-user-status">Developer, Palo Alto</div>
					</div>
				</header>
				<div class="activity-line-action-list">
					<section class="activity-line-action">
						<div class="time">10:40 AM</div>
						<div class="cont">
							<div class="cont-in">
								<p>Uploaded 3 Images to Daily UI Album</p>
								<ul class="previews">
									<li>
										<a class="fancybox" rel="gall-1" href="img/pic.jpg">																	<img src="http://placehold.it/120x80" alt=""/>
										</a>
									</li>
									<li>
										<a class="fancybox" rel="gall-1" href="img/pic.jpg">																	<img src="http://placehold.it/120x80" alt=""/>
										</a>
									</li>
									<li>
										<a class="fancybox" rel="gall-1" href="img/pic.jpg">																	<img src="http://placehold.it/120x80" alt=""/>
										</a>
									</li>
									<li>
										<a class="fancybox" rel="gall-1" href="img/pic.jpg">																	<img src="http://placehold.it/120x80" alt=""/>
										</a>
									</li>
									<li>
										<a class="fancybox" rel="gall-1" href="img/pic.jpg">																	<img src="http://placehold.it/120x80" alt=""/>
										</a>
									</li>
								</ul>
								<ul class="meta">
									<li><a href="#">5 Comments</a></li>
									<li><a href="#">5 Likes</a></li>
								</ul>
							</div>
						</div>
					</section><!--.activity-line-action-->
					<section class="activity-line-action">
						<div class="time">10:40 AM</div>
						<div class="cont">
							<div class="cont-in">
								<p>Left a comment to <a href="#">Olga Gozha’s</a> Image</p>
								<div class="tbl img-comment">
									<div class="tbl-row">
										<div class="tbl-cell tbl-cell-img">
											<img src="http://placehold.it/120x80" alt=""/>
										</div>
										<div class="tbl-cell tbl-cell-txt">
											«Had a meeting about shopping cart experience, with Isobel Patterson, Josh Weller»
										</div>
									</div>
								</div>
								<ul class="meta">
									<li><a href="#">5 Comments</a></li>
									<li><a href="#">5 Likes</a></li>
								</ul>
							</div>
						</div>
					</section><!--.activity-line-action-->
					<section class="activity-line-action">
						<div class="time">10:40 AM</div>
						<div class="cont">
							<div class="cont-in">
								<p>Uploaded 3 files</p>
								<ul class="attach-list">
									<li>
										<i class="font-icon font-icon-page"></i>
										<a href="#">example.avi</a>
									</li>
									<li>
										<i class="font-icon font-icon-page"></i>
										<a href="#">activity.psd</a>
									</li>
									<li>
										<i class="font-icon font-icon-page"></i>
										<a href="#">example.psd</a>
									</li>
								</ul>
								<ul class="meta">
									<li><a href="#">5 Comments</a></li>
									<li><a href="#">5 Likes</a></li>
								</ul>
							</div>
						</div>
					</section><!--.activity-line-action-->
				</div><!--.activity-line-action-list-->
			</article><!--.activity-line-item-->

			<article class="activity-line-item box-typical">
				<div class="activity-line-date">
					Monday<br/>
					sep 8
				</div>
				<header class="activity-line-item-header">
					<div class="activity-line-item-user">
						<div class="activity-line-item-user-photo">
							<a href="#">
								<img src="img/photo-64-2.jpg" alt="">
							</a>
						</div>
						<div class="activity-line-item-user-name">Tim Colins</div>
						<div class="activity-line-item-user-status">Developer, Palo Alto</div>
					</div>
				</header>
				<div class="activity-line-action-list">
					<section class="activity-line-action">
						<div class="time">10:40 AM</div>
						<div class="cont">
							<div class="cont-in">
								<p>Started nes UI migration</p>
								<ul class="meta">
									<li><a href="#">5 Comments</a></li>
									<li><a href="#">5 Likes</a></li>
								</ul>
							</div>
						</div>
					</section><!--.activity-line-action-->
					<section class="activity-line-action">
						<div class="dot"></div>
						<div class="time">10:40 AM</div>
						<div class="cont">
							<div class="cont-in">
								<p>Had a meeting about shopping cart experience, with Isobel Patterson, Josh Weller, Mark Taylor</p>
								<ul class="meta">
									<li><a href="#">5 Comments</a></li>
									<li><a href="#">5 Likes</a></li>
								</ul>
							</div>
						</div>
					</section><!--.activity-line-action-->
					<section class="activity-line-action">
						<div class="time">10:40 AM</div>
						<div class="cont">
							<div class="cont-in">
								<p>Had a meeting about shopping cart experience, with Isobel Patterson, Josh Weller, Mark Taylor</p>
								<ul class="meta">
									<li><a href="#">5 Comments</a></li>
									<li><a href="#">1 Likes</a></li>
								</ul>
							</div>
						</div>
					</section><!--.activity-line-action-->
				</div><!--.activity-line-action-list-->
			</article><!--.activity-line-item-->

			<article class="activity-line-item box-typical">
				<div class="activity-line-date">
					Sunday<br/>
					sep 7
				</div>
				<header class="activity-line-item-header">
					<div class="activity-line-item-user">
						<div class="activity-line-item-user-photo">
							<a href="#">
								<img src="img/photo-64-3.jpg" alt="">
							</a>
						</div>
						<div class="activity-line-item-user-name">Vasilisa</div>
						<div class="activity-line-item-user-status">Product Manager, San Francisco</div>
					</div>
				</header>
				<div class="activity-line-action-list">
					<section class="activity-line-action">
						<div class="time">10:40 AM</div>
						<div class="cont">
							<div class="cont-in">
								<p>Scheduled a meeting for new shopping cart experience with Development team</p>
								<ul class="meta">
									<li><a href="#">5 Comments</a></li>
									<li><a href="#">5 Likes</a></li>
								</ul>
							</div>
						</div>
					</section><!--.activity-line-action-->
					<section class="activity-line-action">
						<div class="time">10:40 AM</div>
						<div class="cont">
							<div class="cont-in">
								<p>Had a meeting about shopping cart experience, with Isobel Patterson, Josh Weller, Mark Taylor</p>
								<div class="alert alert-info">
									New Notification E-Mail: Past Due Request Reminder<br/>
									Recap: For requests, 3 e-mails are generated
								</div>
								<div class="alert alert-danger">
									New Notification E-Mail: Past Due Request Reminder<br/>
									Recap: For requests, 3 e-mails are generated
								</div>
								<div class="alert alert-warning">
									New Notification E-Mail: Past Due Request Reminder<br/>
									Recap: For requests, 3 e-mails are generated
								</div>
								<div class="alert alert-success">
									New Notification E-Mail: Past Due Request Reminder<br/>
									Recap: For requests, 3 e-mails are generated
								</div>
								<div class="alert alert-purple">
									New Notification E-Mail: Past Due Request Reminder<br/>
									Recap: For requests, 3 e-mails are generated
								</div>
								<ul class="meta">
									<li><a href="#">5 Comments</a></li>
									<li><a href="#">5 Likes</a></li>
								</ul>
							</div>
						</div>
					</section><!--.activity-line-action-->
					<div class="activity-line-more">
						<a href="#">See more</a>
					</div>
				</div><!--.activity-line-action-list-->
			</article><!--.activity-line-item-->
		</section><!--.activity-line-->
	</div><!--.container-fluid-->
</div><!--.page-content-->

<script src="js/lib/jquery/jquery.min.js"></script>
<script src="js/lib/tether/tether.min.js"></script>
<script src="js/lib/bootstrap/bootstrap.min.js"></script>
<script src="js/plugins.js"></script>
<script src="js/lib/fancybox/jquery.fancybox.pack.js"></script>
<script>
	$(function() {
		$(".fancybox").fancybox({
			padding: 0,
			openEffect	: 'none',
			closeEffect	: 'none'
		});
	});
</script>
<script src="js/app.js"></script>
</body>

<!-- Mirrored from themesanytime.com/startui/demo/activity.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 18 Nov 2016 18:25:42 GMT -->
</html>