<?php
$rosso = "color:#e74c3c";
$arancione = "color:#e67e22";
$verde = "color:#2ecc71";
$grigio = "color: #95a5a6";
?>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">

            <tr class="bg-danger">
                <th class="text-center">Indice posizione</th>
                <th class="text-center">Gprs</th>
                <th class="text-center">Appezzamento</th>
                <th class="text-center">Stato</th>
                <th class="text-center">Visualizza</th>
                <th class="text-center">Modifica</th>
                <th class="text-center">Elimina</th>
            </tr>

            <tbody>
            <?php foreach ($this->elencoNodi as $nodo): ?>
                <tr>
                    <td style="text-align:center;"><?php echo $nodo['indice-posizione']; ?></td>
                    <td style="text-align:center;"><i class="fa fa-circle" style="<?php
                        if ($nodo->gprs == 0)
                            echo $rosso;
                        else if ($nodo->gprs == 1)
                            echo $verde;
                        ?>
                            "></i></td>
                    <td style="text-align:center;"><?php echo $nodo->idappezzamento ?></td>
                    <td style="text-align:center;"><i class="fa fa-circle" style="<?php
                        if ($nodo->statonodo == 0)
                            echo $verde;
                        else if ($nodo->statonodo == 1)
                            echo $arancione;
                        else if ($nodo->statonodo == 2)
                            echo $rosso;
                        else if ($nodo->statonodo == 3)
                            echo $grigio;
                        ?>"></i></td>
                    <td style="text-align:center;">
                        <a href="<?php echo $this->url(array(
                            "controller" => "admin",
                            "action" => "visualizzanodo",
                            "nodo"=> $nodo->idnodo),
                            "default",true);
                        ?>">
                            <button class="btn btn-warning">Visualizza Nodo</button>
                        </a>
                    </td>
                    <td style="text-align:center;">
                        <a href="<?php echo $this->url(array(
                            "controller" => "admin",
                            "action" => "modificanodo",
                            "nodo"=> $nodo->idnodo)
                            );
                        ?>">
                            <button class="btn btn-primary">Modifica Nodo</button>
                        </a>
                    </td>
                    <td style="text-align:center;">
                        <a href="<?php echo $this->url(array(
                            "controller" => "admin",
                            "action" => "eliminanodo",
                            "nodo"=> $nodo->idnodo)
                            );
                        ?>">
                            <button class="btn btn-danger">Elimina Nodo</button>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <br><br>
        <div align="center">
            <td style="text-align:center;">
                <a href="<?php echo $this->url(array(
                    "controller" => "admin",
                    "action" => "inseriscinodo")
                    
                    )
                ?>">
                    <button class="btn btn-success">Inserisci Nodo</button>
                </a>
            </td>
        </div>
    </div>
</div>





